name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: api
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uuser -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Wait for MySQL
        run: |
          until mysql -h 127.0.0.1 -uuser -ppassword -e "SELECT 1"; do
            echo "Waiting for MySQL to be ready..."
            sleep 2
          done

      - name: Install dependencies
        run: npm install

      - name: Run migrations
        run: npm run migrate

      - name: Run E2E tests
        run: npm test run
